#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Legends.Droid.Resource", IsApplication=true)]

namespace Legends.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int Aatrox = 2130837504;
			
			// aapt resource value: 0x7F02009D
			public const int abilityIcon = 2130837661;
			
			// aapt resource value: 0x7F020001
			public const int Ahri = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Akali = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int Akshan = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int Alistar = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int Amumu = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int Anivia = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int Annie = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int Aphelios = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int Ashe = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int AurelionSol = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int Azir = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int Bard = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int Blitzcrank = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int Brand = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int Braum = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int Caitlyn = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int Camille = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int Cassiopeia = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int Chogath = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int Corki = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int Darius = 2130837525;
			
			// aapt resource value: 0x7F02009E
			public const int detailsIcon = 2130837662;
			
			// aapt resource value: 0x7F020016
			public const int Diana = 2130837526;
			
			// aapt resource value: 0x7F020018
			public const int Draven = 2130837528;
			
			// aapt resource value: 0x7F020017
			public const int DrMundo = 2130837527;
			
			// aapt resource value: 0x7F020019
			public const int Ekko = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int Elise = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int Evelynn = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int Ezreal = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int Fiddlesticks = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int Fiora = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int Fizz = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int Galio = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int Gangplank = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int Garen = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int Gnar = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int Gragas = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int Graves = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int Gwen = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int Hecarim = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int Heimerdinger = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int Illaoi = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int Irelia = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int Ivern = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int Janna = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int JarvanIV = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int Jax = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int Jayce = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int Jhin = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int Jinx = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int Kaisa = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int Kalista = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int Karma = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int Karthus = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int Kassadin = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int Katarina = 2130837559;
			
			// aapt resource value: 0x7F020038
			public const int Kayle = 2130837560;
			
			// aapt resource value: 0x7F020039
			public const int Kayn = 2130837561;
			
			// aapt resource value: 0x7F02003A
			public const int Kennen = 2130837562;
			
			// aapt resource value: 0x7F02003B
			public const int Khazix = 2130837563;
			
			// aapt resource value: 0x7F02003C
			public const int Kindred = 2130837564;
			
			// aapt resource value: 0x7F02003D
			public const int Kled = 2130837565;
			
			// aapt resource value: 0x7F02003E
			public const int KogMaw = 2130837566;
			
			// aapt resource value: 0x7F02003F
			public const int Leblanc = 2130837567;
			
			// aapt resource value: 0x7F020040
			public const int LeeSin = 2130837568;
			
			// aapt resource value: 0x7F020041
			public const int Leona = 2130837569;
			
			// aapt resource value: 0x7F020042
			public const int Lillia = 2130837570;
			
			// aapt resource value: 0x7F020043
			public const int Lissandra = 2130837571;
			
			// aapt resource value: 0x7F02009F
			public const int loreIcon = 2130837663;
			
			// aapt resource value: 0x7F020044
			public const int Lucian = 2130837572;
			
			// aapt resource value: 0x7F020045
			public const int Lulu = 2130837573;
			
			// aapt resource value: 0x7F020046
			public const int Lux = 2130837574;
			
			// aapt resource value: 0x7F020047
			public const int Malphite = 2130837575;
			
			// aapt resource value: 0x7F020048
			public const int Malzahar = 2130837576;
			
			// aapt resource value: 0x7F020049
			public const int Maokai = 2130837577;
			
			// aapt resource value: 0x7F02004A
			public const int MasterYi = 2130837578;
			
			// aapt resource value: 0x7F02004B
			public const int MissFortune = 2130837579;
			
			// aapt resource value: 0x7F02004C
			public const int MonkeyKing = 2130837580;
			
			// aapt resource value: 0x7F02004D
			public const int Mordekaiser = 2130837581;
			
			// aapt resource value: 0x7F02004E
			public const int Morgana = 2130837582;
			
			// aapt resource value: 0x7F02004F
			public const int Nami = 2130837583;
			
			// aapt resource value: 0x7F020050
			public const int Nasus = 2130837584;
			
			// aapt resource value: 0x7F020051
			public const int Nautilus = 2130837585;
			
			// aapt resource value: 0x7F020052
			public const int Neeko = 2130837586;
			
			// aapt resource value: 0x7F020053
			public const int Nidalee = 2130837587;
			
			// aapt resource value: 0x7F020054
			public const int Nocturne = 2130837588;
			
			// aapt resource value: 0x7F020055
			public const int Nunu = 2130837589;
			
			// aapt resource value: 0x7F020056
			public const int Olaf = 2130837590;
			
			// aapt resource value: 0x7F020057
			public const int Orianna = 2130837591;
			
			// aapt resource value: 0x7F020058
			public const int Ornn = 2130837592;
			
			// aapt resource value: 0x7F020059
			public const int Pantheon = 2130837593;
			
			// aapt resource value: 0x7F02005A
			public const int Poppy = 2130837594;
			
			// aapt resource value: 0x7F02005B
			public const int Pyke = 2130837595;
			
			// aapt resource value: 0x7F02005C
			public const int Qiyana = 2130837596;
			
			// aapt resource value: 0x7F02005D
			public const int Quinn = 2130837597;
			
			// aapt resource value: 0x7F02005E
			public const int Rakan = 2130837598;
			
			// aapt resource value: 0x7F02005F
			public const int Rammus = 2130837599;
			
			// aapt resource value: 0x7F020060
			public const int RekSai = 2130837600;
			
			// aapt resource value: 0x7F020061
			public const int Rell = 2130837601;
			
			// aapt resource value: 0x7F020062
			public const int Renekton = 2130837602;
			
			// aapt resource value: 0x7F020063
			public const int Rengar = 2130837603;
			
			// aapt resource value: 0x7F020064
			public const int Riven = 2130837604;
			
			// aapt resource value: 0x7F020065
			public const int Rumble = 2130837605;
			
			// aapt resource value: 0x7F020066
			public const int Ryze = 2130837606;
			
			// aapt resource value: 0x7F020067
			public const int Samira = 2130837607;
			
			// aapt resource value: 0x7F020068
			public const int Sejuani = 2130837608;
			
			// aapt resource value: 0x7F020069
			public const int Senna = 2130837609;
			
			// aapt resource value: 0x7F02006A
			public const int Seraphine = 2130837610;
			
			// aapt resource value: 0x7F02006B
			public const int Sett = 2130837611;
			
			// aapt resource value: 0x7F02006C
			public const int Shaco = 2130837612;
			
			// aapt resource value: 0x7F02006D
			public const int Shen = 2130837613;
			
			// aapt resource value: 0x7F02006E
			public const int Shyvana = 2130837614;
			
			// aapt resource value: 0x7F02006F
			public const int Singed = 2130837615;
			
			// aapt resource value: 0x7F020070
			public const int Sion = 2130837616;
			
			// aapt resource value: 0x7F020071
			public const int Sivir = 2130837617;
			
			// aapt resource value: 0x7F020072
			public const int Skarner = 2130837618;
			
			// aapt resource value: 0x7F020073
			public const int Sona = 2130837619;
			
			// aapt resource value: 0x7F020074
			public const int Soraka = 2130837620;
			
			// aapt resource value: 0x7F020075
			public const int Swain = 2130837621;
			
			// aapt resource value: 0x7F020076
			public const int Sylas = 2130837622;
			
			// aapt resource value: 0x7F020077
			public const int Syndra = 2130837623;
			
			// aapt resource value: 0x7F020078
			public const int TahmKench = 2130837624;
			
			// aapt resource value: 0x7F020079
			public const int Taliyah = 2130837625;
			
			// aapt resource value: 0x7F02007A
			public const int Talon = 2130837626;
			
			// aapt resource value: 0x7F02007B
			public const int Taric = 2130837627;
			
			// aapt resource value: 0x7F02007C
			public const int Teemo = 2130837628;
			
			// aapt resource value: 0x7F02007D
			public const int Thresh = 2130837629;
			
			// aapt resource value: 0x7F02007E
			public const int Tristana = 2130837630;
			
			// aapt resource value: 0x7F02007F
			public const int Trundle = 2130837631;
			
			// aapt resource value: 0x7F020080
			public const int Tryndamere = 2130837632;
			
			// aapt resource value: 0x7F020081
			public const int TwistedFate = 2130837633;
			
			// aapt resource value: 0x7F020082
			public const int Twitch = 2130837634;
			
			// aapt resource value: 0x7F020083
			public const int Udyr = 2130837635;
			
			// aapt resource value: 0x7F020084
			public const int Urgot = 2130837636;
			
			// aapt resource value: 0x7F020085
			public const int Varus = 2130837637;
			
			// aapt resource value: 0x7F020086
			public const int Vayne = 2130837638;
			
			// aapt resource value: 0x7F020087
			public const int Veigar = 2130837639;
			
			// aapt resource value: 0x7F020088
			public const int Velkoz = 2130837640;
			
			// aapt resource value: 0x7F020089
			public const int Vex = 2130837641;
			
			// aapt resource value: 0x7F02008A
			public const int Vi = 2130837642;
			
			// aapt resource value: 0x7F02008B
			public const int Viego = 2130837643;
			
			// aapt resource value: 0x7F02008C
			public const int Viktor = 2130837644;
			
			// aapt resource value: 0x7F02008D
			public const int Vladimir = 2130837645;
			
			// aapt resource value: 0x7F02008E
			public const int Volibear = 2130837646;
			
			// aapt resource value: 0x7F02008F
			public const int Warwick = 2130837647;
			
			// aapt resource value: 0x7F020090
			public const int Xayah = 2130837648;
			
			// aapt resource value: 0x7F020091
			public const int Xerath = 2130837649;
			
			// aapt resource value: 0x7F020092
			public const int XinZhao = 2130837650;
			
			// aapt resource value: 0x7F020093
			public const int Yasuo = 2130837651;
			
			// aapt resource value: 0x7F020094
			public const int Yone = 2130837652;
			
			// aapt resource value: 0x7F020095
			public const int Yorick = 2130837653;
			
			// aapt resource value: 0x7F020096
			public const int Yuumi = 2130837654;
			
			// aapt resource value: 0x7F020097
			public const int Zac = 2130837655;
			
			// aapt resource value: 0x7F020098
			public const int Zed = 2130837656;
			
			// aapt resource value: 0x7F020099
			public const int Ziggs = 2130837657;
			
			// aapt resource value: 0x7F02009A
			public const int Zilean = 2130837658;
			
			// aapt resource value: 0x7F02009B
			public const int Zoe = 2130837659;
			
			// aapt resource value: 0x7F02009C
			public const int Zyra = 2130837660;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
